### ISSUE TITLE
Why are we using such an old display-logic version?

### ISSUE THREAD

**Issue by hailwood** [sheadawson/silverstripe-linkable#16]
display-logic is now up to 1.2.1 so why are we still on 1.0.8?

**Comment by sheadawson** [comment]
It was the most stable version at the time. 1.2.1 is looking good, I've updated linkable to use that version. Cheers!

**Comment by hailwood** [comment]
@sheadawson we broke it!

Looks like there are some issues with display logic 1.2.1 on `TreeDropdownField`s as now if you select the "Page on this website" option the SiteTree field doesn't show.

**Comment by sheadawson** [comment]
Hmm seems we now need to use DisplayLogicWrapper for fields like UploadField and TreeDropdownField. I've fixed in Linkable 1.0.4. Thanks for pointing that out
