### ISSUE TITLE
Link naming gotcha

### ISSUE THREAD

**Issue by jonom** [sheadawson/silverstripe-linkable#49]
Hey Shea, thanks for this dandy module.

Just noticed a bit of a gotcha with the name of the `Link` class. I defined a block with a has_one `'Link' => 'Link'` but of course it doesn't work because Block already has a Link() method. It's a common pattern to use an object's class name as the relation name so wonder if this has tripped other people up too? It's also a bit against SS conventions to get anything but a URL string from `$Link` in templates so I was wondering if you might consider renaming the base class here in the next major version? Maybe `FlexiLink` or something. Then you could maybe rename `LinkURL` to `Link` and things would be a bit more consistent - e.g. doing `$FlexiLink.Link` in templates instead of `$Link.LinkURL`.

**Comment by sheadawson** [comment]
Yo! I think the problem here is the name you gave to the relation? Try calling it has_one ```'FlexiLink' => 'Link'```. That work for ya?

**Comment by jonom** [comment]
Yep! That's effectively what I ended up doing but because it's different to what I normally do I'm sure my brain will fail again at this again in the future. Just wondering if a different class name would reduce confusion for other people too (or maybe it's just me)

**Comment by sheadawson** [comment]
Hmm. I don't feel this is worth renaming the class for personally. Perhaps
just a note in the readme about his potential gotcha

On 28 March 2016 at 10:26, Jono Menz <notifications@github.com> wrote:

> Yep! That's effectively what I ended up doing but because it's different
> to what I normally do I'm sure my brain will fail again at this again in
> the future. Just wondering if a different class name would reduce confusion
> for other people too (or maybe it's just me)
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/sheadawson/silverstripe-linkable/issues/49#issuecomment-202147805>
>



-- 
*Shea Dawson*
Web Developer
LiveSource

*mobile* +64 20 4028 5647
*skype* squatchnz
*email* shea@livesource.co.nz
*web *www.livesource.co.nz

**Comment by jonom** [comment]
No worries!
