### ISSUE TITLE
Having 2 LinkField on the same page will interfere with each other

### ISSUE THREAD

**Issue by maxime-rainville** [sheadawson/silverstripe-linkable#50]
# Starting point
Let's say you have 2 LinkFields on the same DataObject and you are editing your DataObject in the backend.

# Step to reproduce the issue
* Add or Edit a link on the first LinkFiled. Save you changes.
* Try adding or editing a link on the second LinkFiled.
* The Dialogue box doesn't show and the following error is log to the JS Console.
```
Uncaught Error: cannot call methods on dialog prior to initialization; attempted to call method 'open'
```
If you close the first dialogue box (as opposed to saving your changes), the second dialogue box will open fine.

# Possible cause of the problem
I think the problem is cause by the `onunmatch` function on line 66: 
```
$('.linkfield-dialog.ui-dialog-content').remove();
```

I think this line is too generic and will affect all dialogue boxes, not just the one that just got save.

If I comment out line 66, the issue goes away. 

I would do a pull request, but I'm not quite sure what to replace line 66 with ... or if deleting it altogether would have other side affects.

**Comment by sheadawson** [comment]
Thanks for reporting. I can replicate the issue and have had a quick look at it didn't manage to crack it. It seems like we shouldn't be removing ```$('.linkfield-dialog.ui-dialog-content')``` onunmatch because that removes the dialog element for all linkfields. Instead we just want to remove the dialog for the field that has been unmatched. but ``this.getDialog()``` returns nothing in onunmactch so I'm not sure how to find it to delete it. Will have another look as soon as I get some time

**Comment by sheadawson** [comment]
If you need a quick fix just comment out line 66, just means clutter with gather in the dom if lots of link fields are matched/unmatched.

**Comment by grgcnnr** [comment]
Unless I've totally missed the point, we do know which field a dialog belongs to though right?

When they are created a reference to the field is attached as a data attribute" ```this.getDialog().data("field", this)...```

so we couldn't do something like this onunmatch:

```
		onunmatch: function () {
			var self = this;
			$('.linkfield-dialog.ui-dialog-content').filter(function(){
				return self[0] == $(this).data("field")[0];
			}).remove();
		},
```

I'll roll a PR if that makes sense.

**Comment by sheadawson** [comment]
Thanks @grgcnnr, if you've tested it and it works, send me a PR and I'll get it merged in

**Comment by grgcnnr** [comment]
all yours @sheadawson https://github.com/sheadawson/silverstripe-linkable/pull/56

**Comment by sheadawson** [comment]
Works well cheers 👍
