### ISSUE TITLE
Suggestion: enable limitations on the type of oEmbed object allowed

### ISSUE THREAD

**Issue by grgcnnr** [sheadawson/silverstripe-linkable#57]
Currently EmbeddedObjectField will happily consume any valid oembed url.

In my use case, and maybe in other people's It would be useful to restrict it to only Video objects or links, or whatever.

I have a basic version up and running that I can PR if you're interested.
# https://github.com/grgcnnr/silverstripe-linkable/commit/fac086d87026f7499019dc67c5e7a1e6dd541cdd

**Comment by adrexia** [comment]
This would have been really useful for us recently too.

**Comment by sheadawson** [comment]
Limit link types added in #58. Now just need to limit EmbeddedObjectField source urls...
