### ISSUE TITLE
has_many picking up SiteTreeID

### ISSUE THREAD

**Issue by toddkimball** [sheadawson/silverstripe-linkable#70]
I may be, and probably am, misunderstanding the implementation, but the read me says I can attach many link and use a GridField to manage them. So I have the following page:

`private static $has_many = array(
    'ManyLinks'       => 'Link'
);`

And to manage the relation I'm using: 

`$config = GridFieldConfig_RelationEditor::create();
$bishopLinksField = new GridField('ManyLinks', 'ManyLinks', $this->ManyLinks(), $config);`

However, when attempting to add a link, if I choose "Page on this website" I don't get the SiteTree dropdown. Instead I get the Title of the page I'm attempting to add the link to e.g. "Home".

Am I doing this incorrectly and, if so, is there an example of the correct way to do it?

**Comment by gorriecoe** [comment]
As far as I'm aware you need to use a many_many relationship.  has_many relationships need a has_one relationship going back the other way which means it uses the sitetreeID in link object causing your issue.  The following should work with sorting:

```
	/**
	 * @var array
	 */
	private static $many_many = array(
		'ManyLinks' => 'Link',
	);

	/**
	 * @var array
	 */
	private static $many_many_extraFields = array(
		'ManyLinks' => array(
			'Sort' => 'Int'
		)
	);

	/**
	 * @return FieldList
	 */
	public function getCMSFields()
	{
		$fields = parent::getCMSFields();
		$fields->addFieldsToTab(
			'Root.Main',
			array(
				GridField::create(
					'ManyLinks',
					'Links',
					$this->ManyLinks(),
					GridFieldConfig_RelationEditor::create()
						->addComponent(new GridFieldOrderableRows()) // Requires silverstripe-australia/silverstripe-gridfieldextensions
				)
			)
		);
		return $fields;
	}
```

**Comment by toddkimball** [comment]
Ahh, wonderful! Thank you Gorrie.
