### ISSUE TITLE
SS4 migration (Discussion)

### ISSUE THREAD

**Issue by gorriecoe** [sheadawson/silverstripe-linkable#71]
Hey Shea, I'm keen to start migrating linkable to SS4 and think that this will be a perfect time to make some big changes.  Here are just some of my thoughts on it.

- Separate the module into 2, Linkable and Embedable.
- Remove redundancies.  
- Embedable to save images to site so they can be manipulated.
- Linkable to have consistent styles to embedable and uploadfield.  (Move from popup to inline for better mobile experience)

Anyway these are my thoughts.  As I said I'm keen to start migrating but I don't want to make huge changes if everyone disagrees.

Also if anyone else has any ideas feel free to comment 😄

**Comment by sheadawson** [comment]
@gorriecoe I don't have time to work on this at the moment but am more than happy to merge the changes you've proposed should you make any PRs :)

**Comment by sheadawson** [comment]
SS4 upgrade progress in #83

**Comment by ivoba** [comment]
I see #83 is merged. However its still not compatible with SS4 because of unclecheese/silverstripe-display-logic which is not upgraded yet (PRs pending though).
Can someone merge them :)

**Comment by fonsekaean** [comment]
Hello @ivoba, yeah there is an issue with the display logic is not being updated yet. However there you can use our fork to do that. 

https://github.com/SilverStripers/silverstripe-display-logic/

And use ss4-upgrade, just add a VCS in your composer.json and call dev-ss4-upgrade as the version you want to grab in. 

Hopefully display logic will be merged in soon
