### ISSUE TITLE
Anchor links not prepending hash symbol.

### ISSUE THREAD

**Issue by chrispenny** [sheadawson/silverstripe-linkable#80]
Anchor set as part of `Link`:
![screen shot 2017-11-13 at 8 22 21 am](https://user-images.githubusercontent.com/505788/32702430-07b59d5c-c84c-11e7-982e-b532c848d0d1.png)

Resulting link:
![screen shot 2017-11-13 at 8 21 55 am](https://user-images.githubusercontent.com/505788/32702443-3addcfce-c84c-11e7-90f5-2d2527fba221.png)

**Comment by gorriecoe** [comment]
Hey @chrispenny,  this is intentional.  If you read the description below the field it says "Include # at the start of your anchor name or, ? at the start of your querystring".  Maybe the ideal solution would be a check to see if ? or # have not been included on save then prepend #.

**Comment by chrispenny** [comment]
Hah! The description is even in my screen shot. Thank you @gorriecoe for pointing that out - I feel very silly now ^.^

I will close these for now, as I think that's reasonable.

Sorry about this!
