### ISSUE TITLE
composer installation on SS4.1 not working?

### ISSUE THREAD

**Issue by kigi001** [sheadawson/silverstripe-linkable#96]
I use composer for the first time today, so maybe this is due to me not knowing what I do:
I installed SS4.1 via composer with php7.19. Now I wanted to install silverstripe-linkable with the command provided under Readme. I did this by changing directory in cmd to the folder where I installed SS4.1. The following message appeared:
Using version ^1.3 for sheadawson/silverstripe-linkable
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install sheadawson/silverstripe-linkable 1.3.7
    - Conclusion: don't install sheadawson/silverstripe-linkable 1.3.6
    - Conclusion: don't install sheadawson/silverstripe-linkable 1.3.5
    - Conclusion: don't install sheadawson/silverstripe-linkable 1.3.4
    - Conclusion: don't install sheadawson/silverstripe-linkable 1.3.3
    - Conclusion: don't install sheadawson/silverstripe-linkable 1.3.2
    - Conclusion: don't install sheadawson/silverstripe-linkable 1.3.1
    - Conclusion: don't install sheadawson/silverstripe-linkable 1.3.0
    - Conclusion: remove embed/embed v3.3.1
    - Installation request for sheadawson/silverstripe-linkable ^1.3 -> satisfiable by sheadawson/silverstripe-linkable[1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.3.7, 1.3.x-dev].
    - Conclusion: don't install embed/embed v3.3.1
    - sheadawson/silverstripe-linkable 1.3.x-dev requires embed/embed ~2.2.2 -> satisfiable by embed/embed[v2.2.2, v2.2.3, v2.2.4, v2.2.5, v2.2.6, v2.2.7].
    - Can only install one of: embed/embed[v2.2.2, v3.3.1].
    - Can only install one of: embed/embed[v2.2.3, v3.3.1].
    - Can only install one of: embed/embed[v2.2.4, v3.3.1].
    - Can only install one of: embed/embed[v2.2.5, v3.3.1].
    - Can only install one of: embed/embed[v2.2.6, v3.3.1].
    - Can only install one of: embed/embed[v2.2.7, v3.3.1].
    - Installation request for embed/embed (locked at v3.3.1) -> satisfiable by embed/embed[v3.3.1].
Installation failed, reverting ./composer.json to its original content.

Was I missing anything? I assumed composer works like npm when there is a dependency e.g. to the display-logic module that it automatically downloads this as well. I read in a previous issue that someone already installed the display-logic and got an error. Not sure if this one is related to that issue.

**Comment by Greg808** [comment]
I have the same problem.

**Comment by Greg808** [comment]
You need the dev-master version put this in your composer file and it should work. Made the same mistake.   
"sheadawson/silverstripe-linkable": "dev-master"

**Comment by kigi001** [comment]
Hi Greg808,
Thank you very much!!!
You saved my day ;-))
