### ISSUE TITLE
Cant install using Silverstripe v4

### ISSUE THREAD

**Issue by rodwin** [sheadawson/silverstripe-linkable#98]
vagrant@homestead:~/code/myapiary_website$ composer require "sheadawson/silverstripe-linkable"
Using version ^1.3 for sheadawson/silverstripe-linkable
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install sheadawson/silverstripe-linkable 1.3.7
    - Conclusion: don't install sheadawson/silverstripe-linkable 1.3.6
    - Conclusion: don't install sheadawson/silverstripe-linkable 1.3.5
    - Conclusion: don't install sheadawson/silverstripe-linkable 1.3.4
    - Conclusion: don't install sheadawson/silverstripe-linkable 1.3.3
    - Conclusion: don't install sheadawson/silverstripe-linkable 1.3.2
    - Conclusion: don't install sheadawson/silverstripe-linkable 1.3.1
    - Conclusion: don't install sheadawson/silverstripe-linkable 1.3.0
    - Conclusion: remove embed/embed v3.3.3
    - Installation request for sheadawson/silverstripe-linkable ^1.3 -> satisfiable by sheadawson/silverstripe-linkable[1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.3.7, 1.3.x-dev].
    - Conclusion: don't install embed/embed v3.3.3
    - sheadawson/silverstripe-linkable 1.3.x-dev requires embed/embed ~2.2.2 -> satisfiable by embed/embed[v2.2.2, v2.2.3, v2.2.4, v2.2.5, v2.2.6, v2.2.7].
    - Can only install one of: embed/embed[v2.2.2, v3.3.3].
    - Can only install one of: embed/embed[v2.2.3, v3.3.3].
    - Can only install one of: embed/embed[v2.2.4, v3.3.3].
    - Can only install one of: embed/embed[v2.2.5, v3.3.3].
    - Can only install one of: embed/embed[v2.2.6, v3.3.3].
    - Can only install one of: embed/embed[v2.2.7, v3.3.3].
    - Installation request for embed/embed (locked at v3.3.3) -> satisfiable by embed/embed[v3.3.3].

compose.json
```
{
    "name": "silverstripe/installer",
    "type": "silverstripe-recipe",
    "description": "The SilverStripe Framework Installer",
    "require": {
        "php": ">=5.6.0",
        "silverstripe/recipe-plugin": "^1",
        "silverstripe/recipe-cms": "1.1.1@stable",
        "silverstripe-themes/simple": "~3.2.0",
        "cyber-duck/silverstripe-seo": "^4.1",
        "dnadesign/silverstripe-elemental": "2.x-dev",
        "ryanpotter/silverstripe-cms-theme": "^3.0",
        "silverstripe/blog": "^3.1",
        "silverstripe/elemental-blocks": "^1.0",
        "symbiote/silverstripe-gridfieldextensions": "^3.1"
    },
    "require-dev": {
        "phpunit/phpunit": "^5.7"
    },
    "extra": {
        "branch-alias": {
            "4.x-dev": "4.2.x-dev",
            "dev-master": "5.x-dev"
        },
        "project-files-installed": [
            "mysite/.htaccess",
            "mysite/_config.php",
            "mysite/_config/mysite.yml",
            "mysite/code/Page.php",
            "mysite/code/PageController.php"
        ],
        "public-files-installed": [
            ".htaccess",
            "index.php",
            "install-frameworkmissing.html",
            "install.php",
            "web.config"
        ]
    },
    "config": {
        "process-timeout": 600
    },
    "prefer-stable": true,
    "minimum-stability": "dev"
}
```

**Comment by sheadawson** [comment]
Try now

**Comment by rodwin** [comment]
@sheadawson Man you are awesome.
Thanks
